@startuml uc020-sequence-diagram

skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

title Sequence Diagram (SD) - UC020

participant "OperationTypeController" as Controller
participant "OperationTypeService" as Service
participant "OperationType" as Domain
participant "OperationTypeRepository" as Repository
participant "IOperationTypeRepository" as IRepo
participant "CreatingOperationTypeDto" as Dto

-> Controller: POST /api/operationtype \n Body: {name, staffBySpecialization, phasesDuration}

activate Controller

    Controller -> Service: AddAsync(dto)

    activate Service

        Service -> Service: ValidateOperationTypeName(name)

        Service -> Repository: GetByNameAsync(name)

        activate Repository

            Repository -> IRepo: GetByNameAsync(name)
            
            activate IRepo

                IRepo --> Repository: null

            deactivate IRepo

            Repository --> Service: null

        deactivate Repository

        Service -> Domain: new OperationType(dto.getName(), dto.getSpecialization(), dto.getRequiredStaff(), dto.getPhasesDuration())

        activate Domain

            Domain --> Service: operationType

        deactivate Domain

        Service -> Repository: AddAsync(dto)

        activate Repository

            Repository -> IRepo: AddAsync(operationType)

            activate IRepo

                IRepo --> Repository: dto

            deactivate IRepo

            Repository --> Service: dto

        deactivate Repository

        Service --> Controller: dto

    deactivate Service

    <-- Controller : dto

deactivate Controller

@enduml
