@startuml uc020-class-diagram-backend-database

skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

title Class Diagram (CD): Backend Database - UC020

class OperationTypeRepository {
    +GetByNameAsync(name: string): Task<OperationType>
    +AddAsync(dto: CreatingOperationTypeDto): Task<OperationType>
}

interface IOperationTypeRepository {
    +GetByNameAsync(name: string): Task<OperationType>
    +AddAsync(dto: CreatingOperationTypeDto): Task<OperationType>
}

@enduml