@startuml uc020-class-diagram-backend-logic

skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

title Class Diagram (CD): Backend Logic - UC020

class OperationTypeController {
    +GetByName(name: string): Task<ActionResult<OperationTypeDto>>
    +Create(dto: CreatingOperationTypeDto): Task<ActionResult<OperationTypeDto>>
}

class OperationTypeService {
    +GetByNameAsync(name: string): Task<OperationTypeDto>
    +ValidateOperationTypeName(name: string): Task<bool>
    +AddAsync(dto: CreatingOperationTypeDto): Task<OperationTypeDto>
}

class CreatingOperationTypeDto {
    +Name: Name
    +StaffBySpecialization: StaffBySpecialization
    +PhasesDuration: PhasesDuration
    +getName(): Name
    +getStaffBySpecialization(): StaffBySpecialization
    +getPhasesDuration(): PhasesDuration
    +setName(name: Name): void
    +setStaffBySpecialization(staffBySpecialization: StaffBySpecialization): void
    +setPhasesDuration(phasesDuration: PhasesDuration): void
}

class StaffBySpecialization {
    - _staff: Dictionary<Staff, int>
}

class PhasesDuration {
    - _phases: Dictionary<Phase, Duration>
}

enum Phase {
    PREPARATION, SURGERY, CLEANING
}

class Duration {
    + Minutes: int
}

@enduml