@startuml uc020-domain-model.puml

skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

top to bottom direction
left to right direction

hide circle
hide methods

title Domain Model (DM) - UC020

package "OperationTypeAggregate" {
    class OperationType <<root entity>>
    class OperationType <<root entity>>
    class OperationTypeID <<value object>>
    note right of OperationTypeID: unique identifier
    class OperationTypeName <<value object>>
    class RequiredStaff <<value object>>
    class OperationPhaseDetails <<value object>>
    class OperationPhase <<value object>> {
        ANAESTHESIA_PREPARATION, SURGERY_PROCESS, CLEANING
    }
}

class Admin <<conceptual class>>

Admin "1" -- "*" OperationType : creates >
OperationType "1" -- "1" OperationTypeID : > identified by
OperationType "1" -- "1" OperationTypeName : > has
OperationType "1" -- "1" RequiredStaff : > needs
OperationType "1" -- "1..*" OperationPhaseDetails : > has
OperationPhaseDetails "1" -- "1" OperationPhase : > has
OperationPhaseDetails "1" -- "1" Time : > has

@enduml