@startuml SSD-Read

actor User
participant System
participant PostgreSQLDb

activate User
    User -> System : Request Read (include query with filters)
    activate System
    
        System -> System : Validate filters
        
        System -> PostgreSQLDb : Read data
        activate PostgreSQLDb
            
            PostgreSQLDb --> System : Return object
        deactivate PostgreSQLDb
        
        System --> User : Return success/error message
    deactivate System
deactivate User    
@enduml