@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

title System Sequence Diagram (SSD) - UC008
actor Admin as ADM
participant ":System" as System

activate ADM

    ADM -> System: create a new patient profile

    activate System

        System --> ADM: asks to insert the first and last names of\n the patient as well as the full name
    deactivate System

    ADM -> System : Insert required fields
    activate System

        System --> ADM: asks to insert the date of birth of the patient
    deactivate System

    ADM -> System : Insert required field
    activate System

        System --> ADM: asks to insert the gender of the patient
    deactivate System

    ADM -> System : Insert required field
    activate System

        System --> ADM: asks to insert the contact information\n (email, phone number) of the patient
    deactivate System

    ADM -> System : Insert required fields
    activate System

        System -> System: validates email and phone number

    opt
        System --> ADM: asks to insert Allergies/Medical Conditions \nof the patient
        deactivate System

        ADM -> System: insert required field
        activate System

    end opt
        
    System --> ADM: ask to insert emergency contact
    deactivate System

    ADM -> System: insert required field
    activate System

    opt

        System --> ADM: asks to insert the previus or upcaming \nappointment history
        deactivate System

        ADM -> System: insert required field
        activate System

    end opt

        System --> System: generate unique patient ID
        System --> System: creates patient profile
        System --> ADM: show operation success/error
    deactivate System


deactivate ADM

@enduml