@startuml SSD-Create

actor User
participant System
participant AzureSQLDatabase

User -> System : Request Create (include object)
System -> System : Validate object
System -> AzureSQLDatabase : Create object
AzureSQLDatabase --> System : Return success/error message
System --> User : Return success/error message

@enduml