@startuml SSD-Create

actor User
participant System
participant PostgreSQLDb

activate User
    User -> System : Request Create (include object)
    activate System
        
        System -> System : Validate object
        
        System -> PostgreSQLDb : Create object
        activate PostgreSQLDb
            
            PostgreSQLDb --> System : Return success/error message
        deactivate PostgreSQLDb
        
        System --> User : Return success/error message
    deactivate System
deactivate User
        

@enduml