@startuml uc001-domain-model.puml

skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

top to bottom direction
left to right direction

hide circle
hide methods

title Domain Model (DM) - UC001

package "Backoffice Module" {

    package "User Aggregate" {
        class User {
            + Username
            + Role
            + Email
        }
    }

}

@enduml