import { Service } from 'typedi';
import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import path from 'path';
import { Result } from "../core/logic/Result";
import IFileService from './IServices/IFileService';
import { PatientMedicalRecordDto } from '../dto/patient-medical-record/PatientMedicalRecordDto';

@Service()
export default class FileService implements IFileService {

    constructor() {}

    /**
     * Creates a PDF File for a Patient Medical Record.
     * @param patientMedicalRecord 
     */
    public async createFile(patientMedicalRecord: PatientMedicalRecordDto): Promise<Result<string>> {
        try {
            console.log('Creating PDF File for Patient Medical Record...');
            const doc = new PDFDocument({ margin: 50 });
            const fileName = `PatientMedicalRecord_${patientMedicalRecord.medicalRecordNumber.getValue()}.pdf`;

            console.log('File Name: ', fileName);

            const filePath = path.join(__dirname, '../../../files', fileName);
            console.log('File Path: ', filePath);

            if (!fs.existsSync(path.dirname(filePath))) {
                fs.mkdirSync(path.dirname(filePath), { recursive: true });
            }

            const writeStream = fs.createWriteStream(filePath);
            doc.pipe(writeStream);

            // Add Title
            doc.font('Helvetica-Bold').fontSize(20).text('Patient Medical Record', { align: 'center' }).moveDown(1);

            // Add Medical Record Number and Date
            const currentDate = new Date().toLocaleString();
            doc.font('Helvetica').fontSize(10).text(`Medical Record Number: ${patientMedicalRecord.medicalRecordNumber.getValue()}`).moveDown(2);

            // Allergies Section
            doc.font('Helvetica-Bold').fontSize(14).text('Allergies', { underline: true }).moveDown(1);

            if (patientMedicalRecord.allergies.length > 0) {
                const allergiesTable = {
                    headers: ['ICD-11 Code', 'Last Updated', 'Irrelevant'],
                    rows: patientMedicalRecord.allergies.map(allergy => [
                        allergy.code.toString(),
                        new Date(allergy.date).toLocaleDateString(),
                        allergy.notMeaningfulAnyMore ? 'Yes' : 'No'
                    ])
                };
                this.drawTable(doc, allergiesTable);
            } else {
                doc.font('Helvetica').fontSize(12).text('No allergies recorded.', { align: 'left' }).moveDown(1);
            }

            // Medical Conditions Section
            doc.font('Helvetica-Bold').fontSize(14).text('Medical Conditions', { underline: true }).moveDown(1);

            if (patientMedicalRecord.medicalConditions.length > 0) {
                const conditionsTable = {
                    headers: ['ICD-11 Code', 'Last Updated', 'Irrelevant'],
                    rows: patientMedicalRecord.medicalConditions.map(condition => [
                        condition.code.toString(),
                        new Date(condition.date).toLocaleDateString(),
                        condition.notMeaningfulAnyMore ? 'Yes' : 'No'
                    ])
                };
                this.drawTable(doc, conditionsTable);
            } else {
                doc.font('Helvetica').fontSize(12).text('No medical conditions recorded.', { align: 'left' }).moveDown(1);
            }
            
            doc.moveDown(3);

            // Add Footer
            doc.font('Helvetica').fontSize(10).text('Generated by SARM G031 at ' + currentDate + ".", { align: 'center', baseline: 'bottom' });

            // Finalize PDF
            doc.end();

            await new Promise<void>((resolve, reject) => {
                writeStream.on('finish', resolve);
                writeStream.on('error', reject);
            });

            console.log('PDF File created successfully!');

            // Return the file path
            return Result.ok<string>(filePath);

        } catch (error) {
            console.error('Error creating PDF File: ', error);
            return Result.fail<string>(error.message);
        }
    }

    /**
     * Draws a table in the PDF document.
     * @param doc PDFDocument instance
     * @param table Object with headers and rows
     */
    private drawTable(doc: PDFKit.PDFDocument, table: { headers: string[], rows: string[][] }) {
        const startX = doc.x;
        let startY = doc.y; // Usar uma variável para controlar a posição Y
    
        const columnWidths = [100, 200, 150, 100]; // Ajuste as larguras das colunas conforme necessário
    
        // Desenhar os cabeçalhos
        doc.font('Helvetica-Bold').fontSize(10);
        table.headers.forEach((header, i) => {
            doc.text(header, startX + columnWidths.slice(0, i).reduce((a, b) => a + b, 0), startY, {
                width: columnWidths[i],
                align: 'left'
            });
        });
        startY = doc.y + 5; // Ajuste a posição Y após desenhar os cabeçalhos
    
        // Desenhar as linhas
        doc.font('Helvetica').fontSize(10);
        table.rows.forEach(row => {
            row.forEach((cell, i) => {
                doc.text(cell, startX + columnWidths.slice(0, i).reduce((a, b) => a + b, 0), startY, {
                    width: columnWidths[i],
                    align: 'left'
                });
            });
            startY = doc.y + 5; // Atualiza a posição Y após cada linha
        });
    
        doc.moveDown(1);
    }
    
}