@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant System
participant PostgreSQLDb

activate User
    User -> System : Request Delete (include Object)
    activate System
    
        System -> System : Validate Object
        
        System -> PostgreSQLDb : Delete Object
        activate PostgreSQLDb
            
            PostgreSQLDb --> System : Return object
        deactivate PostgreSQLDb
        
        System --> User: Return success/error message
    deactivate System
deactivate User
@enduml