@startuml SSD-Update

actor User
participant System
participant PostgreSQLDb

activate User
    User -> System : Request Update (include data)
    activate System
        
        System -> System : Validate data
        
        System -> PostgreSQLDb : Update data
        activate PostgreSQLDb
            
            PostgreSQLDb --> System : Return object
        deactivate PostgreSQLDb
        
        System --> User : Return success/error message    
    deactivate System
deactivate User
@enduml