@startuml SSD-Update

actor User
participant System
participant AzureSQLDatabase

User -> System : Request Update (include data)
System -> System : Validate data
System -> AzureSQLDatabase : Update data
AzureSQLDatabase --> System : Return object
System --> User : Return success/error message

@enduml