@startuml uc003-sequence-diagram

skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

title Sequence Diagram (SD) - UC003

participant UserController as Controller <<application>>
participant UserService as Service <<service>>
database PatientRepository as PRepository <<repository>>
participant IPatientRepository as IPRepo <<persistence>>
database UserRepository as URepository <<repository>>
participant IUserRepository as IURepo <<persistence>>
participant IAMService as IAMService <<service>>

-> Controller: POST /api/user

activate Controller

    Controller -> Service: AddAsync(dto)

    activate Service

        Service -> Service: ValidatePatientRecord(email)

        Service -> PRepository: GetByEmailAsync(email)

        activate PRepository

            PRepository -> IPRepo: GetByEmailAsync(email)

            activate IPRepo

                IPRepo --> PRepository: patient

            deactivate IPRepo

            PRepository --> Service: patient

        deactivate PRepository

        Service -> URepository: GetByEmailAsync(email)
        
        activate URepository

            URepository -> IURepo: GetByEmailAsync(email)

            activate IURepo

                IURepo --> URepository: user

            deactivate IURepo

            URepository --> Service: user

        deactivate URepository

        Service --> IAMService: RegisterUser(email)

        note right: IAMService is a third-party service\nthat manages user accounts

        activate IAMService

            IAMService --> Service: true

        deactivate IAMService

        Service -> URepository: AddAsync(dto)

        activate URepository

            URepository -> IURepo: AddAsync(dto)

            activate IURepo

                IURepo --> URepository: user

            deactivate IURepo

            URepository --> Service: user

        deactivate URepository

        Service --> Controller: dto

    deactivate Service

    <-- Controller: 201 Created

deactivate Controller

@enduml