@startuml uc003-sequence-diagram

skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

title Sequence Diagram (SD) - UC003

participant ":UserController" as Controller <<application>>
participant ":UserService" as Service <<service>>
participant ":IPatientRepository" as IPRepo <<persistence>>
participant ":IUserRepository" as IURepo <<persistence>>
participant ":IAMService" as IAMService <<service>>

-> Controller: POST /api/user

activate Controller

    Controller -> Service: AddAsync(dto)

    activate Service

        Service -> Service: ValidatePatientRecord(email)

        Service -> IPRepo: GetByEmailAsync(email)

        activate IPRepo

            IPRepo --> Service: patient

        deactivate IPRepo

        Service -> IURepo: GetByEmailAsync(email)
        
        activate IURepo

            IURepo --> Service: user

        deactivate IURepo

        Service -> IAMService: RegisterUser(email)

        activate IAMService

            IAMService --> Service: true

        deactivate IAMService

        Service -> URepository: AddAsync(dto)

        activate URepository

            URepository -> IURepo: AddAsync(dto)

            activate IURepo

                IURepo --> URepository: user

            deactivate IURepo

            URepository --> Service: user

        deactivate URepository

        Service --> Controller: dto

    deactivate Service

    <-- Controller: 201 Created

deactivate Controller

@enduml