@startuml uc003-system-sequence-diagram

title System Sequence Diagram (SSD) - UC003
actor Patient as Patient
participant ":System" as System
participant ":IAM" as IAM

activate Patient

    Patient -> System: Self-register

    activate System

        System --> Patient: Ask for email

    deactivate System

    Patient -> System: Provide email

    alt Exists patient record with email

        activate System

            System --> Patient: Redirect to IAM

        deactivate System

        Patient -> IAM: Provide credentials (email, password)

        activate IAM

            IAM --> Patient: Redirect to System

        deactivate IAM

    else No patient record with email

        activate System

            System --> Patient: Inform that email is not registered as patient and so cannot self-register

        deactivate System

    end

deactivate Patient

@enduml