@startuml uc003-system-sequence-diagram

title System Sequence Diagram (SSD) - UC003
actor Patient as Patient
participant ":System" as System
participant ":IAM" as IAM

activate Patient

    Patient -> System: Self-register

    activate System

        System --> Patient: Redirect to IAM

    deactivate System

    Patient -> IAM: Register

    activate IAM

        IAM --> Patient: Ask for email

    deactivate IAM

    Patient -> IAM: Input email

    activate IAM

        IAM --> Patient: Ask for password

    deactivate IAM

    Patient -> IAM: Input password

    activate IAM

        IAM --> Patient: Confirm registration

        IAM --> System: User email
    
    deactivate IAM

    activate System

        System --> Patient: Redirect to Patient UI

    deactivate System

deactivate Patient

@enduml