@startuml uc003-system-sequence-diagram

title System Sequence Diagram (SSD) - UC003
actor Patient as Patient
participant ":System" as System
participant ":IAM" as IAM

activate Patient

    Patient -> System: Self-register

    activate System

        System --> Patient: Ask for email to check for patient's record existence

    deactivate System

    Patient -> System: Input email

    activate System

        System -> System: Check if patient's record with provided email exists

        System --> Patient: Redirect to IAM

    deactivate System

    Patient -> IAM: Register

    activate IAM

        IAM --> Patient: Ask for email

    deactivate IAM

    Patient -> IAM: Input email

    activate IAM

        IAM --> Patient: Ask for password

    deactivate IAM

    Patient -> IAM: Input password

    activate IAM

        IAM --> Patient: Registration successful

    deactivate IAM

    Patient -> System: Return to system

    activate System

        System --> Patient: Ask for phone number

    deactivate System

    Patient -> System: Input phone number

    activate System

        System --> Patient: Ask for name

    deactivate System

deactivate Patient

@enduml