@startuml uc030-system-sequence-diagram

title System Sequence Diagram (SSD) - UC001
actor Admin as Adm
participant ":IAM" as IAM

activate Adm

    Adm -> IAM: Register Backoffice User
    activate IAM
    
        IAM --> Adm: Ask for new user's username
    deactivate IAM

    Adm -> IAM: Provide new user's username
    activate IAM

        IAM --> Adm: Ask for new user's email
    deactivate IAM

    Adm -> IAM: Provide new user's email
    activate IAM

        IAM --> Adm: Ask for new user's role, giving a set of options\nto choose from (Admin, Doctor, Nurse, Technician)
    deactivate IAM

    Adm -> IAM: Select new user's role
    activate IAM

        IAM -> IAM: Send user confirmation email in order for them to set their password\nand activate their account
        
        IAM --> Adm: User confirmation email sent
    deactivate IAM
deactivate Adm

@enduml